### ISSUE TITLE
Deprecation: constructor vibe.stream.memory.MemoryStream.this is deprecated - Use createMemoryStream instead.

### ISSUE THREAD

**Issue by alexrotaru** [gedaiu/vibe.auth#1]

**Comment by alexrotaru** [comment]
din ce am citit in documentatie, tot ce trebuie facut e sa chemi functia createMemoryStream cu aceeasi parametri cu care chemai inainte constructorul.

**Comment by gedaiu** [comment]
this will be fixed with the next release
